from typing import Final

TOURNAMENT_SET_SIZE: Final[int]=4
TOURNAMENT_PROBABILITY_SELECT_BEST: Final[int]=80
MUTATION_LONGEST_WAIT_PROBABILITY: Final[int]=66
MUTATION_LONGEST_ROUTE_PROBABILITY: Final[int]=66
